-------------------------------------------------------------------------------
-- Program TMP_DOMS_NETWORK_OUTAGE_DETAIL
-------------------------------------------------------------------------------
-- Purpose:  
--   Load data into TMP_DOMS_NETWORK_OUTAGE_DETAIL from rawvalut.
-------------------------------------------------------------------------------
-- Date       | Author                        | Description
-------------------------------------------------------------------------------
-- 2022-07-15 |  Mahesh Kalakonda             | Initial Version
--            |                               |
--            |                               |
--            |                               |
-------------------------------------------------------------------------------

SELECT 
EXTRACT_DATE_TIME,
CUSTOMER_NO,
CUSTOMER_CONNECTION_POINT,
FEEDER,
NMI,
OUTAGE_KEY,
REFERENCE_NUMBER,
ADJ_INTERRUPTION_DATE,
ADJ_RESTORATION_DATE,
DURATION,
FRMP,
INCLUDE_IN_REPORT ,
INTERRUPTION_DATE,
LIFE_SUPPORT,
PROCESS_BY,
REINTERRUPTION,
RESTORATION_DATE,
SITE_VACANT,
SUPPLY_STATE,
UPDATE_TIME,
STAGE_ID,
FEEDER_NO,
CHANGE_TYPE,
LINK_NMI_FEEDER_CUSTOMER_OUTAGE_CUSTOMER_CONNECTION_REFERENCE_HSH_KEY,
LSAT_DOMS_NETWORK_OUTAGE_DETAIL_HSH_DIFF,
RECORD_SOURCE,
LOAD_DATE_TIME
FROM
(
SELECT  
LSNOD.EXTRACT_DATE_TIME,
HC.CUSTOMER_NO,
HCC.CUSTOMER_CONNECTION_POINT,
HF.FEEDER,
HN.NMI,
HO.OUTAGE_KEY,
HR.REFERENCE_NUMBER,
LSNOD.ADJ_INTERRUPTION_DATE,
LSNOD.ADJ_RESTORATION_DATE,
LSNOD.DURATION,
LSNOD.FRMP,
LSNOD.INCLUDE_IN_REPORT ,
LSNOD.INTERRUPTION_DATE,
LSNOD.LIFE_SUPPORT,
LSNOD.PROCESS_BY,
LSNOD.REINTERRUPTION,
LSNOD.RESTORATION_DATE,
LSNOD.SITE_VACANT,
LSNOD.SUPPLY_STATE,
LSNOD.UPDATE_TIME,
LSNOD.STAGE_ID,
LSNOD.FEEDER_NO,
LSNOD.CHANGE_TYPE,
LSNOD.LINK_NMI_FEEDER_CUSTOMER_OUTAGE_CUSTOMER_CONNECTION_REFERENCE_HSH_KEY,
LSNOD.LSAT_DOMS_NETWORK_OUTAGE_DETAIL_HSH_DIFF,
LSNOD.RECORD_SOURCE,
LSNOD.LOAD_DATE_TIME,
ROW_NUMBER() OVER ( PARTITION BY HO.OUTAGE_KEY,HN.NMI,LSNOD.STAGE_ID,LSNOD.INCLUDE_IN_REPORT,LSNOD.ADJ_INTERRUPTION_DATE,LSNOD.ADJ_RESTORATION_DATE,LSNOD.REINTERRUPTION,HR.REFERENCE_NUMBER ORDER BY LSNOD.EXTRACT_DATE_TIME DESC ) AS REC_SEQ
FROM IM${logicalenv}_RAWVAULT.LSAT_DOMS_NETWORK_OUTAGE_DETAIL LSNOD
JOIN IM${logicalenv}_RAWVAULT.LINK_NMI_FEEDER_CUSTOMER_OUTAGE_CUSTOMER_CONNECTION_REFERENCE LNK ON
LSNOD.LINK_NMI_FEEDER_CUSTOMER_OUTAGE_CUSTOMER_CONNECTION_REFERENCE_HSH_KEY = LNK.LINK_NMI_FEEDER_CUSTOMER_OUTAGE_CUSTOMER_CONNECTION_REFERENCE_HSH_KEY
JOIN IM${logicalenv}_RAWVAULT.HUB_CUSTOMER HC ON HC.HUB_CUSTOMER_HSH_KEY = LNK.HUB_CUSTOMER_HSH_KEY
JOIN IM${logicalenv}_RAWVAULT.HUB_CUSTOMER_CONNECTION HCC ON HCC.HUB_CUSTOMER_CONNECTION_HSH_KEY = LNK.HUB_CUSTOMER_CONNECTION_HSH_KEY
JOIN IM${logicalenv}_RAWVAULT.HUB_FEEDER HF ON HF.HUB_FEEDER_HSH_KEY = LNK.HUB_FEEDER_HSH_KEY
JOIN IM${logicalenv}_RAWVAULT.HUB_NMI HN ON HN.HUB_NMI_HSH_KEY = LNK.HUB_NMI_HSH_KEY
JOIN IM${logicalenv}_RAWVAULT.HUB_OUTAGE HO ON HO.HUB_OUTAGE_HSH_KEY = LNK.HUB_OUTAGE_HSH_KEY
JOIN IM${logicalenv}_RAWVAULT.HUB_REFERENCE HR ON HR.HUB_REFERENCE_HSH_KEY = LNK.HUB_REFERENCE_HSH_KEY
)
WHERE REC_SEQ =1 
AND CHANGE_TYPE <> 'D';